### ISSUE TITLE
ListCustomersOptions modifiedSince is not sent in the correct format

### ISSUE THREAD

**Issue by jsypolt** [better-reports/HelpScoutSharp#1]
ToString() is called on queryParams, but HelpScout wants the date in ISO 8601 format (yyyy-MM-dd'T'HH:mm:ss'Z')

Example date passed in 06/15/2021 09:08:07. Note that milliseconds is being added when calling ToString on a DateTime instead of specifying the format as HelpScout expects it.

Help Scout API call failed with code: BadRequest
Reason: 
Content: {"logRef":"3bb98347-c884-48ba-bab9-b2a8bc73f3b3#232118823","message":"Bad request","_embedded":{"errors":[{"path":"modifiedSince","message":"Invalid date - expected ISO 8601 format (yyyy-MM-dd'T'HH:mm:ss'Z')","rejectedValue":"2021-06-15T09:08:07.1234567","source":"query parameter","_links":{"about":{"href":"http://developer.helpscout.net/mailbox-api/overview/errors#IsoDateTime"}}}]},"_links":{"about":{"href":"http://developer.helpscout.net/mailbox-api/overview/errors"}}}

**Comment by clement911** [comment]
Thank you for reporting this!
This is now fixed in 2.6.0 , which I just published to Nuget.
